# Generated by Django 4.2.11 on 2024-04-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image_alter_recipeimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/%y/%m/%d'),
        ),
    ]
